name: Push to main branch workflow

on:
  push:
    branches:
      - main

env:
  authurl: ${{ vars.REACT_APP_AUTHORIZATION_URL }}
  apiurl: ${{ vars.REACT_APP_API_URL }}

jobs:
  dockerize:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Get date
        run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build --build-arg REACT_APP_AUTHORIZATION_URL=${{ env.authurl }} \
          --build-arg REACT_APP_API_URL=${{ env.apiurl }} \
          -t ghcr.io/${{ github.repository }}:${{ env.BUILD_DATE }}-${{ github.sha }} .
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.BUILD_DATE }}-${{ github.sha }}
